# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib zmij, .registration = TRUE
NULL

#' Format doubles with zmij.
#'
#' @noRd
format_double_impl <- function(x) .Call(wrap__format_double_impl, x)

#' Parse doubles with Rust's correctly rounded parser.
#'
#' @noRd
parse_double_impl <- function(x) .Call(wrap__parse_double_impl, x)

# nolint end
